# Generated by Django 4.2.14 on 2024-07-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255, unique=True)),
                ('post_content', models.TextField()),
                ('post_category', models.CharField(max_length=40)),
                ('post_publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
