# Generated by Django 4.2.14 on 2024-07-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postcategory_alter_posttable_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttable',
            name='post_publish_date',
            field=models.DateField(),
        ),
    ]
